import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ReactNode } from "react";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Rof1yev Education",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: { colorPrimary: "#4ade80" },
      }}
    >
      <html lang="en">
        <body className={poppins.className}>
          <section className="bg-slate-700 min-h-screen text-gray-100">
            <main className="container mx-auto">{children}</main>
          </section>
        </body>
      </html>
    </ClerkProvider>
  );
}
